import { Row } from 'native-base'
import { StyleSheet} from 'react-native'


export const Styles = StyleSheet.create({
      bgColor:{
          backgroundColor:'white'
      },
      header:{
        paddingHorizontal:5,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        marginVertical:20,
      },
      inputArea:{
        paddingHorizontal:15,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        width:'98%',
        elevation:5,
        borderRadius:5,
        borderColor:'black',
        borderWidth:0.7,
        height:40,
        backgroundColor:'white'

    },
    input:{
    fontFamily:'Quintessential-Regular',
    paddingHorizontal:10,
    paddingVertical:10,
    fontSize:15,
    width:'90%',
    color:'red',
    height:40,
    fontWeight:'bold'
    },

    title:{
        fontFamily:'Parisienne',
        fontSize:35,
        color:'black',
        paddingHorizontal:15,
    },
    sm_title:{
        fontFamily:'League',
        fontSize:17,
        color:'black',
        paddingHorizontal:1,
        paddingVertical:5
    },

    titleHeader:{
        flexDirection:'row',
        width:'100%',
        alignItems:'center'
    },

    pdH15:{
        paddingHorizontal:15
    },
    container:{
        marginTop:20,
        backgroundColor:'white',
        height:250,
        width:200,
        elevation:7,
        borderRadius:10,
        padding:15,
        marginRight:30,
        marginLeft:2,
        marginBottom:5,
    },
    cover:{
        width:170,
        borderRadius:10,
        height:110,
        
    },
    content:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:10
    },
    dot:{
        width:5,
        height:5,
        borderRadius:5,
        backgroundColor:'red',
        marginHorizontal:5
    },
    description:{
        fontFamily:'Quintessential',
        fontSize:12,
        color:'#4f4a4a'
    },
    cardFooter:{
        flexDirection:'row',
        marginTop:5,
        alignItems:'center',
        width:'100%'
    },
    close:{
        flexDirection:'row',
        marginBottom:10,
        alignItems:'center'
    },
    homeContainer:{
        flexDirection:'row',
        width:260,
        height:70,
        backgroundColor:'white',
        elevation:7,
        padding:6,
        marginVertical:5,
        marginLeft:2,
        marginRight:20,
        borderRadius:10
    },  
    homeCover:{
        borderRadius:10,
        width:60,
        height:60
    },
    homeContent:{
        width:'65%',
        justifyContent:'flex-end',
        height:'100%',
        paddingHorizontal:10,
    },
    TipContainer:{
        height:150,
        width:230,
        marginRight:20,
        borderRadius:10,
        marginBottom:20,
        opacity:0.5,
        backgroundColor:'black',
        marginLeft:3,
        padding:12,
        marginTop:20,
        elevation:7
    },
    TipHouseText:{
        fontFamily:'League',
        fontWeight:'bold',
        color:'#000',
        fontSize:16,
        textShadowColor:'white',
        textShadowRadius:3,
        textShadowOffset:{width:1,height:2}

    },
    TipDescription:{
        fontFamily:'Parisienne',
        color:'white',
        fontSize:16,

    },
    Swiper:{

    },
    slides:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        width:'100%'
    },
    DetailContainer:{
        flex:1,
        backgroundColor:'white'
    },
    SwiperContent:{
        flexDirection:'row',
        height:340,
        width:'100%'
    },
    DetailContent:{
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:20,
        width:'100%',
        marginTop:20,
        marginRight:10
    },
    DetailSubText:{
        fontFamily:'Quintessential',
        fontSize:24,
        color:'#111'
    },
    ratings:{
        fontFamily:'Quintessential',
        fontSize:16,
        color:'#111'
    },
    myStar:{
        color:'#e7a74e',
        backgroundColor:'transparent',
        textShadowColor:'black',
        textShadowOffset:{width:1,height:1},
        textShadowRadius:1
    }


})
